### ISSUE TITLE
Uncaught TypeError: (intermediate value).colors(...).beginAtZero is not a function

### ISSUE THREAD

**Issue by tpalts** [Chartisan/Chartjs#5]
When calling beginAtZero(...), an Error is thrown. Same thing happens, when I call responsive(...).

```
const chart = new Chartisan({
        el: '#chart',
        url: "/get-chart",
        hooks: new ChartisanHooks()
            .colors(['#ECC94B', '#4299E1'])
            .beginAtZero()
            .legend({ position: 'bottom' })
            .title('This is a sample chart using chartisan!')
            .datasets([{ type: 'line', fill: false }, 'bar']),
    });
```

Great package, by the way!

**Comment by xembill** [comment]
same at me! 
is this package work with Echart or ChartJs?

**Comment by ConsoleTVs** [comment]
What error does it throw?

**Comment by tpalts** [comment]
Error shown:
> Uncaught TypeError: (intermediate value).colors(...).beginAtZero is not a function

**Comment by xembill** [comment]
> When calling beginAtZero(...), an Error is thrown. Same thing happens, when I call responsive(...).
> 
> ```
> const chart = new Chartisan({
>         el: '#chart',
>         url: "/get-chart",
>         hooks: new ChartisanHooks()
>             .colors(['#ECC94B', '#4299E1'])
>             .beginAtZero()
>             .legend({ position: 'bottom' })
>             .title('This is a sample chart using chartisan!')
>             .datasets([{ type: 'line', fill: false }, 'bar']),
>     });
> ```
> 
> Great package, by the way!

that because you're using "Echarts Library" just mentions in [Laravel Charts](https://charts.erik.cat/guide/render_charts.html)



    
    <script src="https://unpkg.com/echarts/dist/echarts.min.js"></script>

    

    <script src="https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js"></script>

you should change this to 
 `import { Chartisan } from '@chartisan/chartjs'` 
like in Chartisan documentations

**Comment by tpalts** [comment]
True indeed. Thanks

**Comment by ConsoleTVs** [comment]
Thank you @xembill
